# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4257fdbd29cd1d7347bd9f2ec61b270e"
name = "wishlist"
handle = "wishlist-549"
application_url = "https://attorney-conclude-advertiser-tucson.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "teststoreawais.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://attorney-conclude-advertiser-tucson.trycloudflare.com/auth/callback",
  "https://attorney-conclude-advertiser-tucson.trycloudflare.com/auth/shopify/callback",
  "https://attorney-conclude-advertiser-tucson.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
